version: '3'

services:
  barnbase:
    build: .
    image: barnyard-database
    environment:
      - API_HOST=barnyard-api1
    networks:
      - alpha
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql
    container_name: barnyard-database1

  barnyard-api:
    build: .
    image: barnyard-api
    environment:
      - DB_HOST=barnyard-database1
    networks:
      - alpha
      - beta
    ports:
      - "5000:5000"
    container_name: barnyard-api1
    restart: on-failure
    command: sh -c "sleep 10 && ./main"

  barnyard-web:
    build: .
    image: barnyard-web
    environment:
      - API_URL=
    networks:
      - beta
    ports:
      - "80:80"
    container_name: barnyard-web1

networks:
  alpha:
  beta:
volumes:
  database:
