version: '3'

services:
  barnbase:
    restart: always
    build: .
    image: barnyard-database
    environment:
      - API_HOST=barnyard-api1
    networks:
      - alpha
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql
    container_name: barnyard-database1

  barnyard-api:
    restart: always
    build: .
    image: barnyard-api
    environment:
      - DB_HOST=barnyard-database1
    networks:
      - alpha
      - beta
    ports:
      - "5000:5000"
    container_name: barnyard-api1

  barnyard-notify:
    build: .
    image: barnyard-notify
    environment:
      - DB_HOST=barnyard-database1
    networks:
      - alpha
    container_name: barnyard-notify1


  barnyard-web:
    restart: always
    build: .
    image: barnyard-web
    environment:
      - API_URL=https://api.barnyard.ovh
    networks:
      - beta
    ports:
      - "80:80"
    container_name: barnyard-web1

networks:
  alpha:
  beta:
volumes:
  database:
